### ISSUE TITLE
Error in scan(text = rr[numLines], quiet = TRUE)

### ISSUE THREAD

**Issue by urskalbitzer** [bbolker/glmmadmb#10]
Dear Ben Bolker,
First of all, thanks a lot for developing all these great stats tools for R!

I'm trying to run a model using glmmadbm with the following formula:
`glmmadmb(Leaves ~ Pre_leaves_z, family = "nbinom", data = leaves)`

Running the code (on a Mac) always results in the following error:
`Error in scan(text = rr[numLines], quiet = TRUE) : scan() expected 'a real', got 'obs'`

Before I create a dataset to reproduce this error, I wanted to ask if you already know about it and might know how to fix it?

Thanks a lot,
Urs

**Comment by bbolker** [comment]
Don't know offhand.  A reproducible example would be great, thanks.

**Comment by urskalbitzer** [comment]
I tried:
`data <- data.frame(y = rpois(100, 10), x1 = sample(c("a", "b"), 100, replace = TRUE), x2 = rnorm(100, mean = 0, sd = 1))`
                   
`res <- glmmADMB::glmmadmb(y ~ x1, family = "nbinom", data = data)`

`res <- glmmADMB::glmmadmb(y ~ x2, family = "nbinom", data = data)`

And for both models, I get the message:
> Estimated covariance matrix may not be positive definite
> ...
> Error in scan(text = rr[numLines], quiet = TRUE) : 
  scan() expected 'a real', got 'obs'

I already removed and reinstalled glmmadmb and R2admb but I still get the same error message. It might be a problem with my R or glmmadmb installation. But I'm not sure what else I can try  except reinstalling R and RStudio, which I will do next.

**Comment by bbolker** [comment]
I can't reproduce on Linux, will try on MacOS when I get a chance (soon). (I doubt it's worth reinstalling R/RStudio.)  Other advice is to try moving to the `glmmTMB` package (on CRAN, can do basically everything glmmADMB can ...)

**Comment by urskalbitzer** [comment]
I did a clean re-install of R and RStudio but I still get the same error message (I saw your comment too late). Thanks a lot for the help, I will give a try to glmmTMB.

Urs

PS: `install_packages("R2admb")` is not necessary, the package is automatically installed when running `devtools::install_github("bbolker/glmmadmb")`

**Comment by bbolker** [comment]
OK, I think this should be fixable; there seem to be some extra spaces in the report file on MacOS. I think the proximal problem is actually in `R2admb::read_rep()` ...

**Comment by urskalbitzer** [comment]
I tried glmmTMB and it worked fine.
Please let me know if you are able to fix the issue and I will re-run my models using glmmadmb. I'm curious how similar/different the results are between the two packages. But if this is not a priority for you, I can perfectly live with the results from the glmmTMB model.
Thanks again,
Urs

**Comment by bbolker** [comment]
I think this is fixed now.

**Comment by urskalbitzer** [comment]
Thanks for fixing the bug.
I tried it again with my dataset and glmmadmb works now.

However, results for my dataset (not the example above) appear to be slightly different from the glmmTMB results (I used nbinom2 in both cases). The coefficients are a bit different and my p-value for the term I'm interested in changed from ~0.08 to ~0.11. Also, glmmTMB appears to be much faster.

If you are interested in details, I can share my dataset and code with you.

Urs

**Comment by kmutambanengwe** [comment]
Hello,

This problem still persists on Windows 7. I still get the error even after installing most recent version from github.

Regards,
Kathy

**Comment by bbolker** [comment]
Hmm, that's too bad.  Can you send me a copy of your output files?  (set the `save.dir` function when running `glmmADMB`).  Also, have you considered using glmmTMB instead ... ?

**Comment by kmutambanengwe** [comment]
I attached a zip file of the output files.

I did look at glmmTMB but was also using it together with emmeans package for other things and objects of class glmmTMB are not recognised by emmeans.

[test1.zip](https://github.com/bbolker/glmmadmb/files/2031149/test1.zip)


```
set.seed(123)
data <- data.frame(y = rpois(100,10), x1 = sample(c("a", "b"), 100, replace = TRUE), 
		x2 = rnorm(100, mean = 0, sd = 1))
res <- glmmadmb(y~x1, family = "nbinom", data = data, save.dir = "C:\\Users\\kathy\\Desktop\\test1")
sessionInfo()
```

sessionInfo()
> R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glmmADMB_0.8.5 MASS_7.3-49   

loaded via a namespace (and not attached):
 [1] compiler_3.4.3  Matrix_1.2-12   plyr_1.8.4      magrittr_1.5   
 [5] tools_3.4.3     coda_0.19-1     Rcpp_0.12.16    stringi_1.1.7  
 [9] nlme_3.1-131    grid_3.4.3      stringr_1.3.1   R2admb_0.7.16  
[13] lattice_0.20-35

**Comment by RafaelAlcala** [comment]
Dear Ben Bolker,

Thank you very much for all your work. When I used the glmmADMB package I got the same problem that urskalbitzer. I used the version: glmmADMB 0.8.5, Windows 7 home and R studio 1.1.456.
The model is:
`Mbc01.2 <- glmmadmb(populationtotal ~ treatment+ (1|fdatemonth) + (1|location:fgpsid), 
                                          data = bcartonmerge, 
                                          family = "nbinom")`
The error is:
`Error in scan(text = rr[numLines], quiet = TRUE) : 
  scan() expected 'a real', got 'obs'`

The idea is to compare the diferent levels of treatment with emmeans 

Thanks you

**Comment by bbolker** [comment]
- switching to glmmTMB is always an option (the development version is compatible with emmeans)
- can you try installing latest versions of R2admb and glmmADMB from github (using `devtools::install_github()` or `remotes::install_github()`) and see if that helps?
